services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - wp-volume:/var/www/
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    volumes:
      - db-volume:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 3306
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www
    env_file:
      - .env
    expose:
      - 9000
    networks:
      - inception
    restart: always

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/yait-oul/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/yait-oul/data/mariadb

networks:
  inception:
    driver: bridge
